version: '3.8'

services:
  db:
    image: postgres:15
    container_name: faq_postgres_db
    restart: always
    environment:
      POSTGRES_USER: faq_user
      POSTGRES_PASSWORD: faq_password
      POSTGRES_DB: faq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: