services:
  db:
    image: postgres:15
    container_name: faq_postgres_db
    restart: always
    environment:
      POSTGRES_USER: faq_user
      POSTGRES_PASSWORD: faq_password
      POSTGRES_DB: faq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: faq-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: faq-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data: